### ISSUE TITLE
Selection follows mouse as if the button is stuck down in gnome-terminal.

### ISSUE THREAD

**Issue by nevdelap** [slap-editor/slap#159] opened 2015-05-12 05:13 UTC
Server: bog standard Ubuntu minimal with...
- nginx postgresql memcached binutils gcc make libssl-dev g++ xclip
- latest nodejs.

The problem happens in gnome terminal on two client machines, one of which has all sorts of configuration, but the other is bog standard Ubuntu with unity.

Parts of the interface other than the panel containing the content of the file being edited are fine.

Terminator and xterm are fine.

**Comment by secrettriangle** [comment] 2015-05-12 23:28
Just released a fix. Please update with `npm install -g slap` and confirm!

**Comment by nevdelap** [comment] 2015-05-29 03:49
Hi there. I am very sorry I didn't see this much sooner. I updated, but unfortunately the problem is still there. Updated version is 0.1.28.

**Comment by chjj** [comment] 2015-05-29 04:06
@dbkaplun, sounds like another VTE rabbit hole. Let me know if you find anything funny about the mouse protocol. I think modern VTE uses the SGR mouse sequences.

**Comment by chjj** [comment] 2015-05-29 04:16
@dbkaplun, I think I might know what the cause is here. A while ago, I noticed the latest versions of VTE (gnome-terminal) gets the mouse button mask completely wrong. It's documented in comments here: https://github.com/chjj/blessed/blob/master/lib/program.js#L654

We could check for each VTE version I suppose.

**Comment by dbkaplun** [comment] 2015-11-17 00:20
Closing; let me know if this is still an issue.

**Closed by dbkaplun** 2015-11-17 00:20 UTC
Labels: bug
