### ISSUE TITLE
Release as jxcore package?

### ISSUE THREAD

**Issue by bobef** [slap-editor/slap#185] opened 2015-09-16 06:50 UTC
It would be cool if slap was one executable so I can copy/run it, without installing node, npm, dependencies, pollution in the host os, collisions with the node version on the server(s), blah blah. I think jxcore can help. Never used jxcore myself though, but  looks like the tool for the job of node app to single binary.

**Comment by dbkaplun** [comment] 2015-10-26 12:49
Closing as duplicate of #105, #25.

**Closed by dbkaplun** 2015-10-26 12:49 UTC
Labels: enhancement
