### ISSUE TITLE
save (not saveAs) does not display the filename on save

### ISSUE THREAD

**Issue by nilsgey** [slap-editor/slap#152] opened 2015-04-26 20:52 UTC
When you open an existing file and save with "save", and not "saveAs", is says "saving to undefined" in the top right corner instead of telling the filename.

**Comment by secrettriangle** [comment] 2015-04-27 07:36
Hmm, I cannot reproduce. What file path are you trying to save? Node/npm version?

**Comment by secrettriangle** [comment] 2015-04-27 07:44
Aha, since I removed the default keybinding for `save` I have not tested it. I can confirm now after applying the changes described in #151 to `~/.slap/config`. Will be fixed soon!

**Comment by secrettriangle** [comment] 2015-04-27 07:56
Closed. This fix will be included in the next release of slap!

**Closed** 2015-04-27 07:55 UTC
