### ISSUE TITLE
[confirmed] cursor won't change position visually!

### ISSUE THREAD

**Issue by rahsd** [slap-editor/slap#166] opened 2015-06-11 14:52 UTC
hi;
cursor change position visually only if you type something. arrow keys would change it but you can't see.
thanks

**Comment by mjurczyk** [comment] 2015-06-11 16:22
Possibly duplicate of #164 ? What version of slap do you currently use ?

**Comment by rahsd** [comment] 2015-06-11 16:26
slap@latest
~~~slap@0.1.31, node@0.10.25, v8@3.14.5.9, openssl@1.0.1f, modules@11, zlib@1.2.8, uv@0.10.23, ares@1.10.0, http_parser@1.0~~~

**Comment by mjurczyk** [comment] 2015-06-11 16:39
Update slap to 0.1.32 (which is latest from today) and check if issue still exists.

**Comment by rahsd** [comment] 2015-06-11 16:54
how?
about 2hrs ago; I did `npm install slap@latest`.

**Comment by mjurczyk** [comment] 2015-06-11 17:02
Last PR was merged 6hrs ago and released right after. Try:

```
npm install -g slap@v0.1.32
```

**Comment by rahsd** [comment] 2015-06-11 20:22
it works for now;
thank you
Keep going

**Closed** 2015-06-11 22:08 UTC
